all: result.vcd

result.vcd:d_flip_flop.vhdl tb_d_flip_flop.vhdl
    ghdl -a d_flip_flop.vhdl
    ghdl -a tb_d_flip_flop.vhdl
    ghdl -e tb_d_flip_flop
    ghdl -r tb_d_flip_flop --vcd=result.vcd --stop-time=10us

clean:
    rm -rf result.vcd